openapi: 3.0.0
x-stoplight:
  id: rlt8mlf591ynz
info:
  title: Authentication
  version: '1.0'
  description: ''
servers: []
paths:
  /auth/registration:
    post:
      summary: Register account
      operationId: post-auth-registration
      responses:
        '200':
          description: OK
          content:
            'JSON:API':
              schema:
                type: object
                x-examples:
                  Example 1:
                    data:
                      id: 1
                      type: user
                      attributes:
                        email: joe.doe@infinum.com
                        name: Joe Doe
                        terms_accepted_at: '2023-01-22T14:49:12.525Z'
                properties:
                  data:
                    type: object
                    properties:
                      id:
                        type: integer
                      type:
                        type: string
                        enum:
                          - user
                      attributes:
                        type: object
                        properties:
                          email:
                            type: string
                          name:
                            type: string
                          terms_accepted_at:
                            type: string
              examples:
                Example:
                  value:
                    data:
                      id: 1
                      type: user
                      attributes:
                        email: joe.doe@infinum.com
                        name: Joe Doe
                        terms_accepted_at: '2022-10-01T12:34:21Z'
            HAL:
              schema:
                type: object
                properties: {}
          headers:
            Set-Cookie:
              schema:
                type: string
                example: _web_session=bunchsOfCharacters
            Authorization:
              schema:
                type: string
                example: Bearer toke
      description: ''
      requestBody:
        content:
          'JSON:API':
            schema:
              type: object
              x-examples:
                Example:
                  data:
                    type: registration
                    attributes:
                      email: user@infinum.com
                      first_name: first-name
                      password: password
                      terms_accepted_at: '2023-01-22T14:49:12.525Z'
              properties:
                data:
                  type: object
                  required:
                    - type
                    - attributes
                  properties:
                    type:
                      type: string
                      enum:
                        - registration
                    attributes:
                      type: object
                      required:
                        - email
                        - name
                        - password
                        - terms_accepted_at
                      properties:
                        email:
                          type: string
                        name:
                          type: string
                        password:
                          type: string
                        terms_accepted_at:
                          type: string
                          format: date-time
              required:
                - data
            examples:
              Example:
                value:
                  data:
                    type: registration
                    attributes:
                      email: joe.doe@infinum.com
                      name: Joe Doe
                      password: Super$trongPxxsword
                      terms_accepted_at: '2022-10-01T12:34:21Z'
          HAL:
            schema:
              type: object
              properties:
                email:
                  type: string
                name:
                  type: string
                password:
                  type: string
                terms_accepted_at:
                  type: string
                  format: date-time
              required:
                - email
                - name
                - password
                - terms_accepted_at
            examples:
              Example:
                value:
                  email: joe.doe@infinum.com
                  name: Joe Doe
                  password: Super$trongPxxsword
                  terms_accepted_at: '2022-10-01T12:34:21'
        description: ''
      tags:
        - Authentication
  /auth/sessions:
    post:
      summary: Login
      operationId: post-auth-sessions
      responses:
        '200':
          description: OK
          content:
            'JSON:API':
              schema:
                type: object
                properties:
                  data:
                    type: object
                    properties:
                      id:
                        type: integer
                      type:
                        type: string
                      attributes:
                        type: object
                        properties:
                          access_token:
                            type: string
                          token_type:
                            type: string
                          expires_in:
                            type: integer
                          refresh_token:
                            type: string
                x-examples:
                  Example 1:
                    data:
                      id: 1
                      type: tokens
                      attributes:
                        access_token: 2YotnFZFEjr1zCsicMWpAA
                        token_type: bearer
                        expires_in: 3600
                        refresh_token: tGzv3JOkF0XG5Qx2TlKWIA
              examples:
                Example:
                  value:
                    data:
                      id: 1
                      type: tokens
                      attributes:
                        access_token: 2YotnFZFEjr1zCsicMWpAA
                        token_type: bearer
                        expires_in: 3600
                        refresh_token: tGzv3JOkF0XG5Qx2TlKWIA
          headers:
            Set-Cookie:
              schema:
                type: string
                example: _web_session=123fweer3
              description: _web_session cookie
      requestBody:
        content:
          'JSON:API':
            schema:
              type: object
              properties:
                data:
                  type: object
                  required:
                    - type
                    - attributes
                  properties:
                    type:
                      type: string
                    attributes:
                      type: object
                      required:
                        - email
                        - password
                      properties:
                        email:
                          type: string
                        password:
                          type: string
              required:
                - data
            examples:
              Example:
                value:
                  data:
                    type: sessions
                    attributes:
                      email: user@example.com
                      password: password
      tags:
        - Authentication
      description: ''
    delete:
      summary: Logout
      operationId: delete-auth-sessions
      responses:
        '204':
          description: No Content
      tags:
        - Authentication
      description: ''
tags:
  - name: Authentication
