name: Build

on: push

jobs:
  build:
    name: 'Build'
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v2
      - name: Setup Node.js environment
        uses: actions/setup-node@v3.6.0
        with:
          node-version-file: .tool-versions
          cache: npm
      - name: npm install
        run: npm install
      - name: Build openapi.yaml
        run: npm run build
      - name: S3 copy index.html
        uses: giboow/action-aws-cli@v1
        with:
          args: s3 cp index.html s3://${{secrets.AWS_S3_BUCKET}}/${{github.ref_name}}/index.html
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_S3_BUCKET_REGION }}
      - name: S3 copy build spec
        uses: giboow/action-aws-cli@v1
        with:
          args: s3 cp openapi.yaml s3://${{secrets.AWS_S3_BUCKET}}/${{github.ref_name}}/openapi.yaml
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_S3_BUCKET_REGION }}

