name: Delete

on: delete

jobs:
  build:
    name: 'Delete'
    runs-on: ubuntu-latest
    steps:
      - name: S3 rm
        uses: giboow/action-aws-cli@v1
        with:
          args: s3 rm s3://${{secrets.AWS_S3_BUCKET}}/${{github.event.ref}} --recursive
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: 'eu-west-2'

